import './globals.css'
import Footer from './components/Footer/Footer'
import Navigation from './components/Navigation/Navigation'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Entre Perros || Rock del bueno',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navigation/>

        {children}

        <Footer/>
      </body>
    </html>
  )
}
